/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.io.*;
import javax.swing.JOptionPane;
import static java.lang.Thread.sleep;
/**
 *
 * @author swordz
 */
public class NewJFrame extends javax.swing.JFrame {
int waktu = 0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setLocationRelativeTo(this);       
        jComboBox1.removeAllItems();
        jComboBox1.addItem("1");
        jComboBox1.addItem("2");
        jComboBox1.addItem("3");
        jComboBox1.addItem("4");
        jComboBox1.setSelectedIndex(-1);
        warna();
    }
    
    public void warna() {
        Thread jam = new Thread() {
            public void run() {
                for (;;) {
                    waktu = waktu + 1;
                    switch (waktu) {
                        case 1:
                            jLabel3.setForeground(Color.MAGENTA);
                            break;
                        case 2:
                            jLabel3.setForeground(Color.cyan);
                            break;
                        case 3:
                            jLabel3.setForeground(Color.WHITE); break;
                        case 4:
                            jLabel3.setForeground(Color.black); break;
                        case 5:
                            jLabel3.setForeground(Color.PINK); break;
                        default:
                            waktu = 0;
                            jLabel3.setForeground(Color.YELLOW);
                            break;
                    }
                    try {
                        sleep(200);
                    } catch (InterruptedException e) {
                        
                    }
                }
            }
        };
        jam.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfect World 2 multiclient");
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("PILIH JUMLAH CLIENT:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 180, 290, 60);

        jLabel3.setFont(new java.awt.Font("Gisha", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PERFECT WORLD 2 MULTICLIENT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 90, 790, 80);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(340, 190, 80, 40);

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 51));
        jButton1.setText("RUN");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(430, 190, 140, 40);

        jLabel4.setFont(new java.awt.Font("EucrosiaUPC", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nick: Shilan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 290, 310, 60);

        jLabel5.setFont(new java.awt.Font("EucrosiaUPC", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Perfect World 2 Indonesia");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 380, 520, 60);

        jLabel6.setFont(new java.awt.Font("EucrosiaUPC", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Server: Celestial");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 330, 340, 70);

        jLabel7.setFont(new java.awt.Font("Gisha", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Jika membantu, silakan donasi gold ke:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 270, 470, 40);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 470);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int kos = jComboBox1.getSelectedIndex(); int kos2 = -1;
        if (kos2==kos) {
            //System.out.println("OKE");
            JOptionPane.showMessageDialog(null, "Belum pilih jumlah client","Info",JOptionPane.WARNING_MESSAGE);
            return;
        }
        String jmlh = jComboBox1.getSelectedItem().toString();
        int njmlh = Integer.valueOf(jmlh);
        for (int i=1; i<=njmlh; i++) {
            try {
            //Runtime runtime = Runtime.getRuntime();
            Process process = Runtime.getRuntime().exec("elementclient.exe startbypatcher");               
            } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
            }
        }        
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
